# Bridge clock topic
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Bridge joint states
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Bridge odometry
- ros_topic_name: "odom"
  gz_topic_name: "odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Bridge TF data
- ros_topic_name: "tf"
  gz_topic_name: "world/default/pose/info"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Bridge command velocity
- ros_topic_name: "cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Bridge IMU data
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

#
# NOTE: We're taking care of the image briding via 'ros_gz_image/image_bridge'
# nodes in 'gazebo_sim.launch.py', but they could also be bridged via
# 'ros_gz_bridge/parameter_bridge' as specified via this config file as a
# backup.
#
# Bridge left camera camera_info
- ros_topic_name: "camera/left_camera/camera_info"
  gz_topic_name: "camera/left_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Bridge left camera image
# - ros_topic_name: "camera/left_camera/image_raw"
#   gz_topic_name: "camera/left_camera/image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# Bridge camera info for right camera
- ros_topic_name: "camera/right_camera/camera_info"
  gz_topic_name: "camera/right_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Bridge right camera image
# - ros_topic_name: "camera/right_camera/image_raw"
#   gz_topic_name: "camera/right_camera/image_raw"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# Bridge left RGBD camera point cloud
- ros_topic_name: "camera/left_camera/points"
  gz_topic_name: "camera/left_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
